input.onButtonPressed(Button.A, function () {
    if (true) {
        basic.showIcon(IconNames.Yes)
        basic.pause(3000)
        pins.servoWritePin(AnalogPin.P0, 1)
        basic.pause(1500)
        basic.showNumber(1)
        pins.servoWritePin(AnalogPin.P0, 45)
        basic.pause(1500)
        basic.showNumber(2)
        pins.servoWritePin(AnalogPin.P0, 90)
        basic.pause(1500)
        basic.showNumber(3)
        pins.servoWritePin(AnalogPin.P0, 120)
        basic.pause(1500)
        basic.showNumber(4)
        pins.servoWritePin(AnalogPin.P0, 180)
        basic.pause(1500)
        basic.showNumber(5)
        pins.servoWritePin(AnalogPin.P0, 0)
        basic.pause(1500)
        basic.showNumber(6)
        basic.showString("FIN")
        pins.servoSetPulse(AnalogPin.P0, 0)
        basic.clearScreen()
    }
})
